export const ActionTypes = {
  FETCH_PRODUCT: "FETCH_PRODUCT",
  ADD_TO_CART: "ADD_TO_CART",
  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCTS: "SELECTED_PRODUCTS",
  REMOVE_SELECTED_PRODUCTS: "REMOVE_SELECTED_PRODUCTS",
};
